services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db_postgres
    #   db_postgres:
    # condition: service_healthy
    # volumes:
    #   - ./src:/usr/src/app/src

  db_postgres:
    image: postgres:latest
    container_name: postgres_db2
    restart: always
    volumes:
      - db-data1:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

volumes:
  db-data1:
